const CHANGE_SINGER_LIST = 'singers/CHANGE_SINGER_LIST';
const CHANGE_PAGE_COUNT = 'singers/CHANGE_PAGE_COUNT';
const CHANGE_ENTER_LOADING = 'singers/ENTER_LOADING';
const CHANGE_PULLUP_LOADING = 'singers/PULLUP_LOADING';
const CHANGE_PULLDOWN_LOADING = 'singers/PULLDOWN_LOADING';

export {
  CHANGE_SINGER_LIST,
  CHANGE_PAGE_COUNT,
  CHANGE_ENTER_LOADING,
  CHANGE_PULLDOWN_LOADING,
  CHANGE_PULLUP_LOADING,
};
